version: "3.2"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - AWS_KEY=AKIA3SOANTWBJUENG223
      - AWS_SECRET_ACCESS_KEY=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
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"